### ISSUE TITLE
Tasks don't trickle down to subprojects?

### ISSUE THREAD

**Issue by winglet** [nebula-plugins/gradle-lint-plugin#11]
Hi,
thanks for sharing this work. Not sure what I'm doing wrong but I'm running into trouble when trying to apply to multimodule project:
topmost build.gradle:
```
...
allprojects {
  apply plugin: 'nebula.lint'
  gradleLint.rules = ['dependency-parentheses', 'dependency-tuple']
}
...
```
But when I'm trying to get the report:
```
> gradle generateGradleLintReport
> Could not determine the dependencies of task ':subproject_name:generateGradleLintReport'.
> Task with path 'lintGradle' not found in project subproject_name
```

**Comment by jkschneider** [comment]
@winglet Thanks for the report. We'll get this patched up. This was caused by trying to strike the right balance between making the lint tasks easy to run from any subproject or the root project. 

At one point we had defined all the tasks on every subproject, but the lintGradle tasks on the subprojects only expressed a dependency on root project lintGradle task which actually did something. So to the user they appeared to have the same effect but the subproject tasks were just hollow shells. 

It is necessary that the root task be the effectual one because in Gradle if you run a task from the root project that exists on both the root project and all the subprojects, it will only run the root project task (for example, see all the handwringing on the unexpected behavior of `dependencyInsight` for new Gradle users when the java plugin is applied to the root project inadvertently).

At any rate, I think all this hackery was causing the lint task to be ran multiple times for multi-module projects, which is clearly not desirable.

**Comment by jkschneider** [comment]
Fixed by ed8eeaedcb916d063ac8d713f360e2d1487c742d.

**Comment by winglet** [comment]
Hey. Thanks for the fix. 
Unfortunately still have problems:

```
Error from [com.netflix.nebula.lint.rule.GradleLintRule$1] processing source file [null]
:lintGradle FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':lintGradle'.
> Cannot get property 'isWebjar' on null object

```
